INSERT INTO stock_item_groups (code, name, is_active)
VALUES ('SIG001', 'Electronics', TRUE),
       ('SIG002', 'Furniture', TRUE),
       ('SIG003', 'Clothing', TRUE),
       ('SIG004', 'Footwear', TRUE),
       ('SIG005', 'Kitchen Appliances', TRUE),
       ('SIG006', 'Sporting Goods', TRUE),
       ('SIG007', 'Toys', TRUE),
       ('SIG008', 'Office Supplies', TRUE),
       ('SIG009', 'Cosmetics', TRUE),
       ('SIG010', 'Books', TRUE),
       ('SIG011', 'Pet Supplies', TRUE),
       ('SIG012', 'Automotive Parts', TRUE),
       ('SIG013', 'Industrial Equipment', TRUE),
       ('SIG014', 'Healthcare Products', TRUE),
       ('SIG015', 'Groceries', TRUE),
       ('SIG016', 'Baby Products', TRUE),
       ('SIG017', 'Garden Equipment', TRUE),
       ('SIG018', 'Cleaning Supplies', TRUE),
       ('SIG019', 'Hardware Tools', TRUE),
       ('SIG020', 'Lighting', TRUE),
       ('SIG021', 'Packaging Materials', TRUE),
       ('SIG022', 'Home Decor', TRUE),
       ('SIG023', 'Seasonal Items', TRUE),
       ('SIG024', 'Travel Accessories', TRUE),
       ('SIG025', 'Media & Entertainment', TRUE),
       ('SIG026', 'Safety Equipment', TRUE),
       ('SIG027', 'Medical Equipment', TRUE),
       ('SIG028', 'Jewelry', TRUE),
       ('SIG029', 'Luxury Apparel', TRUE),
       ('SIG030', 'Smart Home Devices', TRUE);