INSERT INTO tags (name, is_active)
VALUES ('Electronics', true),
       ('Home & Kitchen', true),
       ('Health & Personal Care', true),
       ('Sports & Outdoors', true),
       ('Fashion', true),
       ('Toys & Games', true),
       ('Office Supplies', true),
       ('Automotive', true),
       ('Books', true),
       ('Music Instruments', true),
       ('Pet Supplies', true),
       ('Shoes', true),
       ('Mobile Accessories', true),
       ('Laptop Accessories', true),
       ('Beauty', true),
       ('Grocery', true),

       ('Seasonal', false),
       ('Clearance', false),
       ('Rare Collectibles', false),
       ('Limited Edition', false),
       ('Damaged Packaging', false),
       ('Refurbished', false),
       ('Used Goods', false),

       ('Eco-Friendly', true),
       ('Budget', true),
       ('Luxury', true),
       ('Trending', true),
       ('Premium', true),
       ('Exclusive', true);
